# Generated by Django 6.1.1 on 2026-09-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorprofile',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='tutor_cvs/'),
        ),
    ]
