# Generated by Django 6.1.1 on 2026-09-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0002_remove_tutorprofile_date_of_birth_tutorprofile_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='hourly_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='qualification',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
