# Generated by Django 6.1.1 on 2026-09-25 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_subject_remove_grade_order'),
        ('tutors', '0003_alter_tutorprofile_hourly_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorprofile',
            name='hourly_fee',
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_locations', to='core.location'),
        ),
        migrations.CreateModel(
            name='TutorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='tutors.tutorprofile')),
            ],
            options={
                'ordering': ['day', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TutorTeaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutor_teachings', to='core.grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutor_teachings', to='core.subject')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachings', to='tutors.tutorprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tutor', 'subject', 'grade'), name='unique_tutor_subject_grade')],
            },
        ),
    ]
