# Generated by Django 6.1.1 on 2026-09-30 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0004_remove_tutorprofile_hourly_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorprofile',
            name='qualification',
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='experience',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Experience in years', null=True),
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('study_field', models.CharField(blank=True, max_length=100, null=True)),
                ('degree_name', models.CharField(blank=True, max_length=200, null=True)),
                ('college', models.CharField(blank=True, max_length=200, null=True)),
                ('university', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='tutors.tutorprofile')),
            ],
        ),
    ]
