# Generated by Django 6.1.1 on 2026-09-10 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_location'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.grade'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='core.location'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='school_college',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
