# Generated by Django 6.1.1 on 2026-09-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentprofile_gender_alter_studentprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('school', 'School'), ('plus_two', '+2'), ('bachelor', 'Bachelor'), ('master', 'Master')], max_length=20),
        ),
    ]
