# Generated by Django 6.1.1 on 2026-09-15 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_city_district_region_alter_location_address_and_more'),
        ('students', '0004_studentprofile_education_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='address',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='core.location'),
        ),
    ]
