# Generated by Django 6.1.1 on 2026-09-25 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_subject_remove_grade_order'),
        ('students', '0005_remove_studentprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_location', to='core.location'),
        ),
    ]
